version: "3.0"

services:
  importify:
    #build section only uses defaults for now
    build:
      context: .
      dockerfile: Dockerfile
    image: importify
    ports:
      - "3333:3333"
    volumes:
      - ./app/:/app/
